# fly.toml file generated for phoenixdiff-web-prod on 2022-10-18T21:26:13-06:00

app = "phoenixdiff-web-prod"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  ALLOWED_ORIGINS= "//phoenixdiff.org //*.phoenixdiff.org"
  HONEYBADGER_ENV_NAME="Production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
