# fly.toml app configuration file generated for phoenixdiff-logshipper-prod on 2024-04-04T22:45:38-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phoenixdiff-logshipper-prod'
primary_region = 'den'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  image = 'ghcr.io/superfly/fly-log-shipper:latest'

[env]
  ORG = 'phoenixdiff-prod'

[[services]]
  protocol = 'tcp'
  internal_port = 8686
  processes = ['app']

[services.concurrency]
  type = 'connections'
  hard_limit = 25
  soft_limit = 20

[[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'
