name: Smoke tests
run-name: Smoke testing ${{ inputs.environment }} by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to test"
        type: environment
        required: true

  workflow_call:
    inputs:
      environment:
        description: "The environment to test"
        type: string
        required: true

jobs:
  rainforest:
    name: Rainforest
    runs-on: ubuntu-latest
    steps:
      - name: Look up environment
        id: lookup_environment_id
        run: |
          echo "environment_id=$(if [ '${{ inputs.environment }}' == 'Production' ]; then echo '55737'; else echo '55736'; fi)" >> $GITHUB_OUTPUT
      - name: Rainforest
        uses: rainforestapp/github-action@master
        with:
          token: ${{ secrets.RAINFOREST_API_TOKEN }}
          run_group_id: 13018
          environment_id: ${{ steps.lookup_environment_id.outputs.environment_id}}
          cache_key: ${{ inputs.environment }}
